
language: java
jdk:
  - oraclejdk11


before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

script: 
- mvn clean install
- mvn -Dmaven.javadoc.skip=true verify
- java -jar /home/travis/.m2/repository/de/novatec/marioai/marioAI/1.8/marioAI-1.8.jar




