
language: java
jdk:
  - oraclejdk10
git:
lfs_skip_smudge: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: 
- mvn clean install
- "lein deps; lein javac; export DISPLAY=:99.0; ./lazytest.sh"
- java -jar /home/travis/build/NovaTecConsulting/MarioAI/target/marioAI-1.8.jar



