
language: java
jdk:
  - oraclejdk11
git:
lfs_skip_smudge: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
script: 
- mvn clean install
- java -jar /home/travis/.m2/repository/de/novatec/marioai/marioAI/1.8/marioAI-1.8.jar



